name: Daily Randomized Commits

on:
  schedule:
    - cron: "0 7 * * *"
    - cron: "0 12 * * *"
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  daily-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "Ik-cyber"
          git config --global user.email "numterminal@gmail.com"

      - name: Randomized Multi-Commits
        run: |
          if [ $(( RANDOM % 2 )) -eq 0 ]; then
            echo "Skipping this run to simulate random behavior."
            exit 0
          fi

          num_commits=$(( RANDOM % 4 + 1 ))
          echo "Making $num_commits commits in this run."

          for i in $(seq 1 $num_commits)
          do
            echo "Random commit $i on $(date)" >> daily-log.md
            git add daily-log.md
            git commit -m "Random commit $i on $(date)"
            sleep $(( RANDOM % 30 + 5 ))
          done

      - name: Push changes if there are commits
        run: |
          if git diff --cached --quiet; then
            echo "No changes to push."
            exit 0
          fi

          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}