name: Daily Commit

on:
  schedule:
    - cron: "0 7 * * *" # Runs every day at 7 AM UTC

jobs:
  daily-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update daily log
        run: |
          echo "Daily update: $(date)" >> daily-log.md

      - name: Configure Git
        run: |
          git config --global user.name "Ik-cyber"
          git config --global user.email "numterminal@gmail.com"

      - name: Commit changes
        run: |
          git add daily-log.md
          git commit -m "Daily log update: $(date)" || echo "Nothing to commit"
          git push
