name: Daily Randomized Commits

on:
  schedule:
    - cron: "0 7 * * *" # Runs every day at 7 AM UTC
    - cron: "0 12 * * *" # Additional run at 12 PM UTC
    - cron: "0 17 * * *" # Additional run at 5 PM UTC
  workflow_dispatch: # Optional: allows manual runs for testing

jobs:
  daily-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "Ik-cyber"
          git config --global user.email "numterminal@gmail.com"

      - name: Randomized Multi-Commits
        run: |
          # Randomly decide whether to skip this run (50% chance)
          if [ $(( RANDOM % 2 )) -eq 0 ]; then
            echo "Skipping this run to simulate random behavior."
            exit 0
          fi

          # Random number of commits between 1 and 4
          num_commits=$(( RANDOM % 4 + 1 ))
          echo "Making $num_commits commits in this run."

          for i in $(seq 1 $num_commits)
          do
            echo "Random commit $i on $(date)" >> daily-log.md
            git add daily-log.md
            git commit -m "Random commit $i on $(date)"
            sleep $(( RANDOM % 30 + 5 ))  # Sleep between 5 and 35 seconds
          done

          git push
